In [1]:
languages = ['java', 'python', 'javascript']
versions = [1,2,3]

print(list(zip(languages, versions)))

[('java', 1), ('python', 2), ('javascript', 3)]


In [4]:
import pandas as pd
df = pd.DataFrame(list(zip(languages, versions)), columns = ['col1', 'col2'])
df

col1  col2
0        java     1
1      python     2
2  javascript     3

Pandas

In [5]:
data = {"name": ['Tom', 'Nick', 'Krish', 'Jack'], 'age': [24, 25, 26, 27]}
df = pd.DataFrame(data)
df

name  age
0    Tom   24
1   Nick   25
2  Krish   26
3   Jack   27

In [13]:
#series
df['age']

0    24
1    25
2    26
3    27
Name: age, dtype: int64

In [14]:
df['age'].head(3)

0    24
1    25
2    26
Name: age, dtype: int64

In [16]:
df['type'] = df['age'].apply(lambda x: 'fresher' if x <= 25 else 'not a fresher')
df

name  age           type
0    Tom   24        fresher
1   Nick   25        fresher
2  Krish   26  not a fresher
3   Jack   27  not a fresher

In [19]:
import numpy as np
arr1 = np.zeros((3,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr2 = np.ones((2,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [204]:
import random
arr = np.zeros((100,100))
for i in range(len(arr)):
    for j in range(len(arr[i])):
        arr[i][j] = random.randint(1,100)
arr

array([[ 60.,  89.,  87., ...,   9.,  16.,  84.],
       [ 59.,  10.,  60., ...,  41.,   8.,  66.],
       [ 44.,  33., 100., ...,  65.,  30.,  63.],
       ...,
       [ 53.,  88.,  92., ...,  22.,  70.,  94.],
       [ 41.,   4.,   7., ...,  40.,   7.,   6.],
       [ 72.,  69.,   6., ...,  29.,  49.,  60.]])

In [205]:
arr1 = np.transpose(arr)
arr1

array([[ 60.,  59.,  44., ...,  53.,  41.,  72.],
       [ 89.,  10.,  33., ...,  88.,   4.,  69.],
       [ 87.,  60., 100., ...,  92.,   7.,   6.],
       ...,
       [  9.,  41.,  65., ...,  22.,  40.,  29.],
       [ 16.,   8.,  30., ...,  70.,   7.,  49.],
       [ 84.,  66.,  63., ...,  94.,   6.,  60.]])

In [207]:
arr2 = np.reshape(arr, (20,500))
arr2

array([[60., 89., 87., ..., 94., 57., 71.],
       [26., 22., 62., ..., 88., 27., 98.],
       [38., 46., 48., ..., 30.,  4., 38.],
       ...,
       [84., 58., 14., ..., 87., 83., 48.],
       [32., 16., 83., ..., 10., 60., 97.],
       [ 3., 76., 37., ..., 29., 49., 60.]])